# Generated by Django 4.1.3 on 2022-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Investment', 'Investment')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Debt', 'Debt'), ('Food', 'Food'), ('Electricity', 'Electricity'), ('Car', 'Car'), ('Petrol', 'Petrol'), ('Property', 'Property'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
