# Generated by Django 4.1.3 on 2022-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_earning_category_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
